# 服务配置
server:
  port: 9001 #端口
  tomcat:
    uri-encoding: UTF-8
    max-connections: 500
    min-spare-threads: 25
    max-threads: 300
    accept-count: 200

spring:
  profiles:
    active: test
    include:     #后续添加的配置文件

# mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.jijl.mist.modules #实体类
  executor-type: simple
  configuration:
    auto-mapping-unknown-column-behavior: none
    auto-mapping-behavior: partial
    cache-enabled: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      field-strategy: not_empty
      db-type: mysql
      id-type: id_worker
    banner: false
