spring:
  ## 数据库相关配置
  datasource:
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      connection-init-sqls: set names utf8mb4;
      url: jdbc:p6spy:mysql://127.0.0.1:3306/jijl?useUnicode=true&useSSL=false
      #      driver-class-name: com.mysql.cj.jdbc.Driver
      #      connection-init-sqls: set names utf8mb4;
      #      url: jdbc:mysql://47.106.169.138:3306/jijl?useUnicode=true&useSSL=false
      username: root
      password: jijl
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  # redis相关配置
  redis:
    database: 1
    host: 127.0.0.1
    password: jijilan..
    port: 6380
    timeout: 6000ms  # 连接超时时长（毫秒）
